import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { Fira_Code } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar/Navbar";


const fira = Fira_Code({ subsets: ['greek'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={` bg-[#f7f7f5]`}
        >
          <Navbar />
          <Toaster />
          {children}
        </body>
      </html>
    </SessionWrapper>
    
  );
}
